"""
Django settings for Emeeting project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sm)aup$o2-7#6x!=65fb60m1gb_acaz0myyh^k+aa00e9e-a3k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','393dfbcfa94d.ngrok.io','192.168.0.90','125.99.153.203']
#ALLOWED_HOSTS = ['44ce4c7c8e90.ngrok.io']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'EmeetingApp',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Emeeting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Emeeting.wsgi.application'


# Database
# https://docs.djangoproject.com/e
#
#
#
# n/3.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }

# -------------------Mgenuis Db------------------
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'emeeting_admin',
    #     'USER': 'botuser',
    #     'PASSWORD': 'Botuser@2020',
    #     'HOST': '202.66.172.133',
    #     'PORT': '3306',
    # }
# -------------------Linux Db------------------
# 'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'emeeting',
#         'USER': 'root',
#         'PASSWORD': 'Redhat@2020',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# -------------------Local Db ------------------
'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'emeeting',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Channels settings
ASGI_APPLICATION = "Emeeting.asgi.application"
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('localhost', 6379)],
#             #"symmetric_encryption_keys": [SECRET_KEY],
#         },
#     },
# }
CHANNEL_LAYERS = {
    'default': {
        #'BACKEND': 'channels_redis.core.RedisChannelLayer',
        "BACKEND": "channels.layers.InMemoryChannelLayer",
        # 'CONFIG': {
        #     "hosts": [('https://421fc8c08dbe.ngrok.io', 6379)],
        # },
    },
}




# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


# Sessions expire when the user closes the browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#Sessions expire after a period of inactivity:
#SESSION_COOKIE_AGE = 10


